### ISSUE TITLE
Analog Stick and digipad are swapped with a generic pc controller

### ISSUE THREAD

**Issue by MaggoLive** [retrospy/RetroSpy#165] opened 2020-09-13 21:22 UTC
i got a generic pc controller with a digipad. When i use the generic pc skin (the xbox controller) the inputs from the digipad are shown as inputs of the left analog stick. Can i fix this by changing the code in the xml file?

**Comment by zoggins** [comment] 2020-09-15 03:33
Sorry just seeing this.  I am not entirely sure the specific controller, but its highly likely you can change the skin.xml file for the PC controller skin.

**Comment by wertercatt** [comment] 2021-07-09 02:15
> i got a generic pc controller with a digipad. When i use the generic pc skin (the xbox controller) the inputs from the digipad are shown as inputs of the left analog stick. Can i fix this by changing the code in the xml file?

A lot of generic PC controllers send their d-pads as 'analog' input. No idea why.

**Comment by 40wattrange** [comment] 2021-11-17 22:49
This can be resolved by adjusting the skin file. This is not a bug of the application.

**Comment by zoggins** [comment] 2021-12-01 18:35
If this is a still a problem what controller is it?

**Comment by zoggins** [comment] 2021-12-09 17:40
closing from inactivity.  Feel free to repopen if necessary.

**Closed by zoggins** 2021-12-09 17:40 UTC
Labels: more info needed
